# Generated by Django 2.2.5 on 2022-05-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ans1', models.IntegerField(default=0)),
                ('ans2', models.IntegerField(default=0)),
                ('ans3', models.IntegerField(default=0)),
                ('ans4', models.IntegerField(default=0)),
                ('ans5', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('choice1', models.CharField(max_length=50)),
                ('choice2', models.CharField(max_length=50)),
                ('choice3', models.CharField(max_length=50)),
                ('choice4', models.CharField(max_length=50)),
                ('choice5', models.CharField(max_length=50)),
                ('answer', models.IntegerField(default=1)),
            ],
        ),
    ]
